language: node_js
node_js:
  - '7.7.3'
install:
  - npm install --production
notifications:
  email:
      - sales@sidrilling.co.uk
      - rpprroger@gmail.com
before_script:
  - npm run lint
script:
  - export NODE_ENV=production
  - npm run build
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      export NODE_ENV="development";
    fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      export TRACKING_CODE="UA-96594891-2";
      export NODE_ENV="production";
    fi
  - npm run deploy-drafts;
branches:
  only:
    - develop
    - master
