language: node_js
addons:
  ssh_known_hosts:
  - ssh.phx.nearlyfreespeech.net
node_js:
- 9.11.1
install:
- npm install --production
notifications:
  email:
  - sales@sidrilling.co.uk
  - rpprroger@gmail.com
before_script:
- npm run lint
script:
- if [ "$TRAVIS_BRANCH" == "develop" ]; then
    export NODE_ENV="development";
    export SCP_USERNAME=$NFS_DRAFT;
  fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then
    export TRACKING_CODE="UA-96594891-2";
    export NODE_ENV="production";
    export SCP_USERNAME=$NFS_PROD;
  fi
- npm run build
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ ! -z "$SCP_USERNAME" ]; then
    rsync -aP -e "ssh -i deploy-keys/draft" build/ $SCP_USERNAME@$SCP_HOST:/home/public
  fi
branches:
  only:
  - develop
  - master
  - /^greenkeeper/.*$/
before_install:
- openssl aes-256-cbc -K $encrypted_3a54c86f385b_key -iv $encrypted_3a54c86f385b_iv
  -in deploy-keys/draft.enc -out deploy-keys/draft -d
- chmod 600 deploy-keys/draft
