language: node_js
node_js:
  - '7.7.3'
install:
  - npm install --production
notifications:
  email:
      - sales@sidrilling.co.uk
      - rpprroger@gmail.com
before_script:
  - npm run lint
  - npm run build
script:
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
      npm run deploy-drafts;
    fi
branches:
  only:
    - develop
    - master